matrix:
  include:
    - os: linux
      language: android
      licenses:
        - 'android-sdk-preview-license-.+'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'
      android:
        components:
          - tools
          - platform-tools
          - build-tools-25.0.3
          - android-25
          - sys-img-armeabi-v7a-google_apis-25
          - extra-android-m2repository
          - extra-google-m2repository
          - extra-google-android-support
      jdk: oraclejdk8
      sudo: false
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libstdc++6
            - fonts-droid
      before_script:
        - ./scripts/before_script_android.sh
      script:
        - ./scripts/script_android.sh

    - os: osx
      language: generic
      osx_image: xcode8.3
      before_script:
        - ./scripts/before_script_ios.sh
      script:
        - ./scripts/script_ios.sh

cache:
  directories:
- $HOME/.pub-cache
